#Linear Regression


In [3]:
import tensorflow as tf
import random

In [4]:
tf.__version__

'2.6.0'

In [ ]:
!pip uninstall tensorflow

tensorflow version을 2.6.0 에서 1.13.1으로 다운그레이드 해줍니다.

In [ ]:
!pip install tensorflow==1.13.1

In [52]:
import tensorflow as tf
import random

In [53]:
tf.__version__

'1.13.1'

In [54]:
hello=tf.constant("Hello, Tensorflow!")
sess=tf.Session()
print(sess.run(hello))

b'Hello, Tensorflow!'


In [55]:
x_train=[1,2,3]
y_train=[1,2,3]

In [56]:
import numpy as np
print(np.array(x_train).shape)
print(np.array(y_train).shape)

(3,)
(3,)


In [57]:
# Try to find value for W and b to compute y_data = x_data + W + b
# We know that W should be 1 and b shoud be 0
# But let's TensorFlow figure it out

W=tf.Variable(tf.random_normal([1]), name="weight") # tf.random_normal: 난수 생성
b=tf.Variable(tf.random_normal([1]), name='bias')

print("W: ", W)
print("b: ", b)

W:  <tf.Variable 'weight_3:0' shape=(1,) dtype=float32_ref>
b:  <tf.Variable 'bias_5:0' shape=(1,) dtype=float32_ref>


In [58]:
# Out hypothesis WX +b
hypothesis=x_train*W + b

print("hypothesis: ", hypothesis)

hypothesis:  Tensor("add_8:0", shape=(3,), dtype=float32)


In [59]:
cost=tf.reduce_mean(tf.square(hypothesis - y_train))

print("cost :", cost)

cost : Tensor("Mean_5:0", shape=(), dtype=float32)


In [60]:
optimizer= tf.train.GradientDescentOptimizer(learning_rate=0.01)
train=optimizer.minimize(cost)

print("optimizer: ", optimizer)
print("train: ", train)

optimizer:  <tensorflow.python.training.gradient_descent.GradientDescentOptimizer object at 0x7ff3bfdd2910>
train:  name: "GradientDescent_4"
op: "NoOp"
input: "^GradientDescent_4/update_weight_3/ApplyGradientDescent"
input: "^GradientDescent_4/update_bias_5/ApplyGradientDescent"



In [61]:
# Launch the graph in a session
sess=tf.Session()

# initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

print("sess: ", sess)

sess:  <tensorflow.python.client.session.Session object at 0x7ff3bff23b10>


In [62]:
for step in range(4001):
  sess.run(train)
  if step%200 ==0:
    print(step, sess.run(cost), sess.run(W), sess.run(b))

0 28.44174 [-1.0682838] [-0.9220759]
200 5.756226e-06 [1.0027866] [-0.00633448]
400 2.1983185e-06 [1.0017222] [-0.00391473]
600 8.4004733e-07 [1.0010644] [-0.00241974]
800 3.2114687e-07 [1.0006584] [-0.00149626]
1000 1.2296913e-07 [1.0004075] [-0.00092564]
1200 4.7147193e-08 [1.0002525] [-0.00057303]
1400 1.8102606e-08 [1.0001565] [-0.00035498]
1600 7.0042887e-09 [1.0000974] [-0.00022063]
1800 2.6793192e-09 [1.0000604] [-0.00013664]
2000 1.026598e-09 [1.0000371] [-8.480505e-05]
2200 3.8592063e-10 [1.0000229] [-5.1792e-05]
2400 1.5780326e-10 [1.0000148] [-3.298118e-05]
2600 7.3863284e-11 [1.0000101] [-2.22746e-05]
2800 3.8181014e-11 [1.0000075] [-1.6155172e-05]
3000 2.4690175e-11 [1.0000061] [-1.26953155e-05]
3200 1.7158422e-11 [1.0000051] [-1.0696562e-05]
3400 1.480771e-11 [1.0000048] [-9.6836675e-06]
3600 1.336294e-11 [1.0000044] [-9.068131e-06]
3800 1.2628713e-11 [1.0000043] [-8.695797e-06]
4000 1.22781785e-11 [1.0000043] [-8.61273e-06]


#Multi_Linear regression


In [63]:
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]

y_data = [152., 185., 180., 196., 142.]

In [64]:
print(np.array(x1_data).shape) 
print(np.array(x2_data).shape)
print(np.array(x3_data).shape)
print(np.array(y_data).shape)

(5,)
(5,)
(5,)
(5,)


In [65]:
print(type(x1_data[0]))

<class 'float'>


In [66]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

print(x1)
print(type(x1))

Tensor("Placeholder_12:0", dtype=float32)
<class 'tensorflow.python.framework.ops.Tensor'>


In [67]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [68]:
print(w1)
print(w2)
print(w3)
print(b)

<tf.Variable 'weight1_2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'weight2_2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'weight3_2:0' shape=(1,) dtype=float32_ref>
<tf.Variable 'bias_6:0' shape=(1,) dtype=float32_ref>


In [69]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [70]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(4001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 50 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  184720.55 
Prediction:
 [-235.18262 -270.36108 -272.8553  -294.08707 -205.95895]
50 Cost:  9.83531 
Prediction:
 [146.21513 187.94943 178.7788  197.72112 143.59973]
100 Cost:  9.640656 
Prediction:
 [146.2682  187.91342 178.79555 197.7294  143.55571]
150 Cost:  9.451083 
Prediction:
 [146.32057 187.87788 178.81207 197.73755 143.5123 ]
200 Cost:  9.266405 
Prediction:
 [146.37227 187.84282 178.8284  197.74554 143.46951]
250 Cost:  9.086523 
Prediction:
 [146.4233  187.80823 178.84451 197.7534  143.42732]
300 Cost:  8.911287 
Prediction:
 [146.47366 187.7741  178.86046 197.76114 143.38574]
350 Cost:  8.740618 
Prediction:
 [146.52335 187.74039 178.87616 197.7687  143.34473]
400 Cost:  8.574358 
Prediction:
 [146.57242 187.70718 178.89168 197.77614 143.30432]
450 Cost:  8.412324 
Prediction:
 [146.62083 187.67435 178.907   197.78342 143.26445]
500 Cost:  8.254553 
Prediction:
 [146.66861 187.64197 178.92212 197.79059 143.22516]
550 Cost:  8.100832 
Prediction:
 [146.71579 187.610

# Logisitic classification

In [71]:
x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

In [72]:
import numpy as np

np_x=np.array(x_data)
print("x_data shape: ", np_x.shape)
np_y=np.array(y_data)
print("y_data shape: ", np_y.shape)

x_data shape:  (6, 2)
y_data shape:  (6, 1)


In [73]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [74]:
print(X)
print(Y)

Tensor("Placeholder_16:0", shape=(?, 2), dtype=float32)
Tensor("Placeholder_17:0", shape=(?, 1), dtype=float32)


In [75]:
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [76]:
# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

In [77]:
print(hypothesis)

Tensor("Sigmoid_1:0", shape=(?, 1), dtype=float32)


In [78]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

In [79]:
train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)
print(train)

name: "GradientDescent_6"
op: "NoOp"
input: "^GradientDescent_6/update_weight_4/ApplyGradientDescent"
input: "^GradientDescent_6/update_bias_7/ApplyGradientDescent"



In [80]:
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

print(predicted)
print(accuracy)

Tensor("Cast_2:0", shape=(?, 1), dtype=float32)
Tensor("Mean_8:0", shape=(), dtype=float32)


In [81]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: \n", h, "\nCorrect (Y): \n", c, "\nAccuracy: \n", a)

0 2.3877084
200 0.6711727
400 0.5587769
600 0.50548136
800 0.4737152
1000 0.45091328
1200 0.4324238
1400 0.41631794
1600 0.4017177
1800 0.38819143
2000 0.37551078
2200 0.36354515
2400 0.35221305
2600 0.3414587
2800 0.33123967
3000 0.3215213
3200 0.3122734
3400 0.30346873
3600 0.29508182
3800 0.28708908
4000 0.2794684
4200 0.27219868
4400 0.26525998
4600 0.2586336
4800 0.25230196
5000 0.24624841
5200 0.24045722
5400 0.2349137
5600 0.22960402
5800 0.22451533
6000 0.21963541
6200 0.21495277
6400 0.21045677
6600 0.20613746
6800 0.2019854
7000 0.19799167
7200 0.19414811
7400 0.1904469
7600 0.18688078
7800 0.1834429
8000 0.18012692
8200 0.17692673
8400 0.17383671
8600 0.17085148
8800 0.16796614
9000 0.16517588
9200 0.16247623
9400 0.15986317
9600 0.15733254
9800 0.15488079
10000 0.1525043

Hypothesis: 
 [[0.03201613]
 [0.16054088]
 [0.31091398]
 [0.77863324]
 [0.93782926]
 [0.9795847 ]] 
Correct (Y): 
 [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy: 
 1.0


# softmax classification

In [82]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [83]:
np_x=np.array(x_data)
np_y=np.array(y_data)

print(np_x.shape)
print(np_y.shape)

(8, 4)
(8, 3)


In [84]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

print(X)
print(Y)
print(nb_classes)

Tensor("Placeholder_18:0", shape=(?, 4), dtype=float32)
Tensor("Placeholder_19:0", shape=(?, 3), dtype=float32)
3


In [85]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

print(W)
print(b)

<tf.Variable 'weight_5:0' shape=(4, 3) dtype=float32_ref>
<tf.Variable 'bias_8:0' shape=(3,) dtype=float32_ref>


In [86]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

print(hypothesis)

Tensor("Softmax_1:0", shape=(?, 3), dtype=float32)


In [87]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

print(cost)
print(optimizer)

Tensor("Mean_9:0", shape=(), dtype=float32)
name: "GradientDescent_7"
op: "NoOp"
input: "^GradientDescent_7/update_weight_5/ApplyGradientDescent"
input: "^GradientDescent_7/update_bias_8/ApplyGradientDescent"



In [88]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(3001):
            _, cost_val = sess.run([optimizer, cost], feed_dict={X: x_data, Y: y_data})

            if step % 200 == 0:
                print(step, cost_val)

    print('--------------')
    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')
    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')
    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')
    all = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 8.033653
200 0.597852
400 0.48521376
600 0.38766763
800 0.29535112
1000 0.24244502
1200 0.21907765
1400 0.19975376
1600 0.18348299
1800 0.1695908
2000 0.15759382
2200 0.14713283
2400 0.13793463
2600 0.12978683
2800 0.12252177
3000 0.11600567
--------------
[[1.7604638e-03 9.9823761e-01 1.9033653e-06]] [1]
--------------
[[0.89419657 0.10117535 0.00462812]] [0]
--------------
[[2.3672031e-10 7.1662151e-05 9.9992836e-01]] [2]
--------------
[[1.7604638e-03 9.9823761e-01 1.9033653e-06]
 [8.9419657e-01 1.0117535e-01 4.6281200e-03]
 [2.3672031e-10 7.1662158e-05 9.9992836e-01]] [1 0 2]
